######################################################################
#
# File name : counter_tb.udo
# Created on: Thu Jan 13 18:03:10 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
