######################################################################
#
# File name : fp_arbitor_8_tb_compile.do
# Created on: Mon Jan 17 15:44:28 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Modeltech_pe_10.4c\\win32pe\\vlib work
D:\\Modeltech_pe_10.4c\\win32pe\\vlib msim

D:\\Modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

D:\\Modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\Modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../EDA_Design.srcs/sources_1/new/fp_arbitor_8.v" \
"../../../EDA_Design.srcs/sources_1/new/fp_arbitor_8_tb.v" \


# compile glbl module
D:\\Modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

