######################################################################
#
# File name : fp_arbitor_8_tb_wave.do
# Created on: Mon Jan 17 15:44:40 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
